title: International School of Music Bondi
description: Australia's leading institution for group and private music education
baseurl: ""
url: "https://ismbondi.com.au" # the base hostname & protocol for your site
# Build settings
# markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-sitemap
