theme: jekyll-theme-cayman
title: International School of Music Bondi
description: We Teach Music Differently

url: "https://ismbondi.com.au" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
