theme: jekyll-theme-cayman
title: Welcome to International School of Music Bondi
description: We Teach Music Differently
<h1> For ages 2-adults

<img src="images/International School of Music Bondi.png" alt="ismbondi" width="500" height="500">
