theme: jekyll-theme-cayman
title: Welcome to International School of Music Bondi!
description: We Teach Music Differently! *For ages 2- adults*

![Image of Yaktocat](https://github.com/LyxiaW/ISMB/commit/157f98600783a7926c650ae7c608145413b4c2d7#diff-1a420e6f6e9dc34e0e2e5f8b562ac19e)
