theme: jekyll-theme-cayman
title: Welcome to International School of Music Bondi!
description: We Teach Music Differently! *For ages 2- adults*

![Image of Yaktocat](https://octodex.github.com/images/yaktocat.png)
